-- Verified reception / quotation records for the public "名人与书籍评价" archive.
-- Sources are preserved as structured JSON so the public UI can show the quotation first and the source second.

insert into public.entries (slug,category,zh,en,ja,sources,status,version) values
('peng-qizi','人物',jsonb_build_object('title','彭器资','summary','北宋诗人、文臣。其《送许屯田》诗留下了现存较早的景德镇地区制瓷赞语之一。','meta',jsonb_build_object('kind','person','era','北宋','quote','浮梁巧烧瓷，颜色比琼玖。','quote_original','浮梁巧烧瓷，颜色比琼玖。','quote_work','《送许屯田》','quote_context','诗中以“琼玖”比喻浮梁所烧瓷器的色泽与质地。','role','诗人、文臣')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://zh.wikisource.org/zh-hans/容齋隨筆/卷四','label','《容斋随笔》卷四·浮梁陶器')),'published',1),
('qianlong-emperor','人物',jsonb_build_object('title','乾隆皇帝','summary','清高宗弘历，清代宫廷陶瓷的重要鉴赏者。其御制诗曾直接赞咏景德镇郎窑红等名瓷。','meta',jsonb_build_object('kind','person','era','清','quote','世上朱砂非所拟，西方宝石致难同。','quote_original','世上朱砂非所拟，西方宝石致难同。','quote_work','《赏钧红》／郎窑红釉器御制诗','quote_context','故宫藏郎窑红釉穿带直口瓶外底刻有乾隆御制诗，诗中将红釉之美与西方宝石相比。','role','皇帝、鉴赏者')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://www.dpm.org.cn/collection/ceramic/227155.html','label','故宫博物院·郎窑红釉穿带直口瓶')),'published',1),
('yin-hong-xu','人物',jsonb_build_object('title','殷弘绪（François-Xavier d’Entrecolles）','summary','法国耶稣会士。18世纪初在景德镇长期观察制瓷生产，并将景德镇瓷业与工艺介绍到欧洲。','meta',jsonb_build_object('kind','person','era','清·康熙—雍正时期','quote','The beautiful porcelain, which is a vivid and sparkling white, and of a beautiful and celestial blue, all comes from Jingdezhen.','quote_original','The beautiful porcelain, which is a vivid and sparkling white, and of a beautiful and celestial blue, all comes from Jingdezhen.','quote_translation','美丽的瓷器，有明亮闪耀的白色，也有美丽的天青色，皆出自景德镇。','quote_work','Letters on porcelain manufacture, 1712','quote_context','殷弘绪在景德镇考察制瓷，并根据实地观察、工匠口述和中文资料记录景德镇瓷业。','role','法国耶稣会士、观察者')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://www.gotheborg.com/letters/','label','Selected Passages from the Letters of Père d’Entrecolles')),'published',1),
('guo-moruo','人物',jsonb_build_object('title','郭沫若','summary','现代文学家、历史学家。20世纪中叶访问景德镇后留下多首与景德镇陶瓷有关的诗作。','meta',jsonb_build_object('kind','person','era','现代','quote','中华向号瓷之国，瓷业高峰是此都。','quote_original','中华向号瓷之国，瓷业高峰是此都。','quote_work','《题与艺术瓷厂》','quote_context','郭沫若参观景德镇艺术瓷厂时题诗，评价景德镇在中国瓷业中的地位。','role','文学家、历史学家')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://credit.jdz.gov.cn/cms/content/queryOfPreview.action?contentId=25152','label','景德镇官方资料·景德镇：不熄的窑火之城')),'published',1),
('tian-han','人物',jsonb_build_object('title','田汉','summary','现代戏剧家、诗人。曾以诗歌赞誉景德镇陶瓷艺术家及其作品。','meta',jsonb_build_object('kind','person','era','现代','quote','禹鼎凌烟笔意殊，曾家绝艺蜚瓷都。','quote_original','禹鼎凌烟笔意殊，曾家绝艺蜚瓷都。','quote_work','《赠曾龙升先生》','quote_context','田汉观看曾龙升的瓷雕《钟馗》后所作题赠诗句，评价其艺术造诣。','role','戏剧家、诗人')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://mt.sohu.com/20170804/n505431027.shtml','label','景德镇陶瓷艺术史料整理')),'published',1),
('joseph-needham','人物',jsonb_build_object('title','李约瑟（Joseph Needham）','summary','英国科学史家。《中国科学技术史》研究中，他特别关注景德镇的制瓷工业与城市组织。','meta',jsonb_build_object('kind','person','era','现代','quote','景德镇是世界上最早的工业城市。','quote_original','景德镇是世界上最早的工业城市。','quote_work','《中国科学技术史》·陶瓷相关研究','quote_context','李约瑟考察景德镇并研究中国科技史后，对景德镇以制瓷业支撑城市发展的历史地位作出概括。','role','科学史家')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://paper.people.com.cn/rmrbhwb/html/2020-06/18/content_1992823.htm','label','人民日报海外版·景德镇对世界意味着什么')),'published',1),
('longfellow','人物',jsonb_build_object('title','Henry Wadsworth Longfellow（亨利·沃兹沃思·朗费罗）','summary','美国诗人。其长诗《Keramos》以诗意想象描绘18世纪景德镇窑火与外销瓷。','meta',jsonb_build_object('kind','person','era','19世纪','quote','Above the town of King-te-tching, / A burning town, or seeming so,— / Three thousand furnaces that glow','quote_original','Above the town of King-te-tching, / A burning town, or seeming so,— / Three thousand furnaces that glow','quote_translation','飞越景德镇上空，那是一座燃烧的城，仿佛如此——三千座窑炉持续发光。','quote_work','《Keramos》','quote_context','诗中以夜间窑火描写景德镇，并将瓷器写成从烟囱间飘向世界市场的“瓷叶”。','role','诗人')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://www.gutenberg.org/files/67970/67970-h/67970-h.htm','label','Project Gutenberg·Chinese Pottery and Porcelain')),'published',1),
('rl-hobson','人物',jsonb_build_object('title','R. L. Hobson（罗伯特·洛克哈特·霍布森）','summary','英国陶瓷史学者。其《中国陶器与瓷器》记录了20世纪初景德镇的城市与窑业景象。','meta',jsonb_build_object('kind','person','era','20世纪初','quote','This is perhaps what struck me most forcibly in Ching-tê Chên—that it is unlike anything else in China.','quote_original','This is perhaps what struck me most forcibly in Ching-tê Chên—that it is unlike anything else in China.','quote_translation','最强烈打动我的，也许正是景德镇与中国其他地方截然不同。','quote_work','Chinese Pottery and Porcelain, Vol. I','quote_context','霍布森描述景德镇长期以制瓷业为核心形成的独特城市面貌。','role','陶瓷史学者')), '{}'::jsonb,'{}'::jsonb,jsonb_build_array(jsonb_build_object('url','https://www.gutenberg.org/files/67970/67970-h/67970-h.htm','label','Project Gutenberg·Chinese Pottery and Porcelain')),'published',1)
on conflict (slug) do update set zh=excluded.zh, sources=excluded.sources, category=excluded.category, status='published', updated_at=now();

update public.entries
set zh=jsonb_set(zh,'{meta}',(coalesce(zh->'meta','{}'::jsonb)-'quote'-'quote_original'-'quote_work'-'quote_context')||jsonb_build_object('quote','厂窑至此，集大成矣！','quote_original','厂窑至此，集大成矣！','quote_work','《陶说》／唐英相关制瓷记述','quote_context','唐英评价景德镇厂窑制瓷发展至此，已达到集大成的程度。'),true), updated_at=now()
where slug='tang-ying';
